URL support for parsing (issue #77)
arran4/golang-ical pull request #78
Opened 2023-09-24 11:23 UTC by Courtcircuits

In response to issue #77, I have made some improvements to the codebase. Specifically, I have added a new method `ParseCalendarFromUrl(string)` and a new test case that verifies the absence of errors when invoking this method.

Currently, this method initializes a basic `http.Client` and forwards the response body to the `ParseCalendar(string)` function. However, as suggested in issue #77, it may be beneficial to allow users to use a custom `http.Client` to address authentication, CORS, and similar concerns.

I am currently exploring the best design approach to accommodate this feature request. Any input or suggestions on the optimal design for this enhancement would be greatly appreciated.

2023-10-19 19:34 UTC, james-elastic commented
This would be a great help if it was integrated. Thank you!

2023-10-19 21:40 UTC, arran4 commented
Okay noted. I will (try to make time to...) mock the active HTTP get and make what ever changes necessary to do that this weekend. Unless  it's something either of you want to do? @james-elastic @Courtcircuits

2023-10-20 13:23 UTC, Courtcircuits commented
By the way, I can enhance this pull request. Currently, there isn't much to it. I'm considering implementing the "functional option pattern" to instantiate the HTTP client (more about this pattern :  [YouTube video](https://www.youtube.com/watch?v=MDy7JQN5MN4)).

@arran4, I can also include a few more tests (like mock of HTTP connection). I recognize that the ones I added may not be entirely relevant.

2023-10-21 02:39 UTC, arran4 commented
The functional options pattern is fine, however just a var-args with a type swtich could do as we don't really need meta information around the http.Client.

I am not sure if more tests are warranted as there isn't much logic, definitely need to test the http.Options solution. Also for people have need custom headers, ie authorization, post, etc. You might want to split it into two (or more) functions, where the http.Request is created in the Get and passed to a http.Do function, which itself is also a constructor. 

Please try use fmt.Errorf to wrap the errors if it adds value.

2023-10-21 02:46 UTC, arran4 requested changes
As discussed.

2023-10-24 23:08 UTC, arran4 requested changes

2023-10-24 23:08 UTC, arran4 commented on calendar_test.go
> +	cal, err := ParseCalendarFromUrl(url)
This looks like it would be making a real HTTPS request in tests. It should be using a mock http client.

2023-10-24 23:08 UTC, arran4 commented on README.md
> +    cal, err := ParseCalendar("an-ics-url")
Minor, but an example URL + a http client custom example might be nice. I've been contemplating making this more readable.

2024-09-28 08:35 UTC, arran4 commented
Resolved conflicts in https://github.com/arran4/golang-ical/pull/102

2024-09-28 13:18 UTC, arran4 commented
@Courtcircuits I created a new PR to up date this, can you please review it: https://github.com/arran4/golang-ical/pull/102

I will merge it (or make more changes) in the coming days if no response.

2024-10-15 12:09 UTC, merged

2024-10-15 12:09 UTC, arran4 commented
Yay!